name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  report:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run test-coverage --if-present
      - name: Run codacy-coverage-reporter
        uses: mrfyda/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        env:
          PORT: 3000
