name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  report:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - name: Run coverage script
        run: npm run test-coverage --if-present
        env:
          PORT: 3000
          DB_URI: ${{ secrets.DB_URI }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          DG_HOST: ${{ secrets.DG_HOST }}
          DG_TOKEN: ${{ secrets.DG_TOKEN }}
          DG_NAME: ${{ secrets.DG_NAME }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Run codacy-coverage-reporter
        uses: mrfyda/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
